post_build:
  commands:
    - echo Push image to ECR
    - docker push 732203471303.dkr.ecr.ap-south-1.amazonaws.com/migration-demo:latest

    # ECS deploy
    - aws ecs update-service --cluster migration-cluster --service migration-demo-service --force-new-deployment

    # EKS deploy
    - aws eks update-kubeconfig --region ap-south-1 --name <your-eks-cluster>
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
